const discBrands = [
  { label: 'Above Ground Level' },
  { label: 'AquaFlight' },
  { label: 'Axiom Discs' },
  { label: 'Birdie' },
  { label: 'Clash Discs' },
  { label: 'Climo Disc Golf' },
  { label: 'Crosslap' },
  { label: 'Daredevil Discs' },
  { label: 'DGA' },
  { label: 'Discmania' },
  { label: 'Discraft' },
  { label: 'Disctroyer' },
  { label: 'Divergent' },
  { label: 'Dynamic Discs' },
  { label: 'Elevation Disc Golf' },
  { label: 'EV-7' },
  { label: 'Finish Line' },
  { label: 'Gateway' },
  { label: 'Hooligan Discs' },
  { label: 'Infinite Discs' },
  { label: 'Innova' },
  { label: 'Jester Disc Golf' },
  { label: 'Kastaplast' },
  { label: 'Latitude 64' },
  { label: 'Legacy' },
  { label: 'Lightning' },
  { label: 'Lone Star Discs' },
  { label: 'Løft Discs' },
  { label: 'Millennium' },
  { label: 'Mint Discs' },
  { label: 'MVP' },
  { label: 'Neptune Discs' },
  { label: 'Other' },
  { label: 'Prodigy' },
  { label: 'Prodiscus' },
  { label: 'RPM' },
  { label: 'Sacred Discs' },
  { label: 'Stokely Discs' },
  { label: 'Storm' },
  { label: 'Streamline' },
  { label: 'Thought Space Athletics' },
  { label: 'Trash Panda' },
  { label: 'Vibram' },
  { label: 'Viking' },
  { label: 'Westside Discs' },
  { label: 'Wild Discs' },
  { label: 'Yikun' },
];

export default discBrands;