const discBrands = [
  'Above Ground Level',
  'AquaFlight',
  'Axiom Discs',
  'Birdie',
  'Clash Discs',
  'Climo Disc Golf',
  'Crosslap',
  'Daredevil Discs',
  'DGA',
  'Discmania',
  'Discraft',
  'Disctroyer',
  'Divergent',
  'Dynamic Discs',
  'Elevation Disc Golf',
  'EV-7',
  'Finish Line',
  'Gateway',
  'Hooligan Discs',
  'Infinite Discs',
  'Innova',
  'Jester Disc Golf',
  'Kastaplast',
  'Latitude 64',
  'Legacy',
  'Lightning',
  'Lone Star Discs',
  'Løft Discs',
  'Millennium',
  'Mint Discs',
  'MVP',
  'Neptune Discs',
  'Other',
  'Prodigy',
  'Prodiscus',
  'RPM',
  'Sacred Discs',
  'Stokely Discs',
  'Storm',
  'Streamline',
  'Thought Space Athletics',
  'Trash Panda',
  'Vibram',
  'Viking',
  'Westside Discs',
  'Wild Discs',
  'Yikun'
];

export default discBrands;
